site_name: AI Engineer Guide
theme:
    name: 'material'
    palette:
        # primary: 'purple'
      # Light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: purple
        accent: purple
        toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to dark mode
      # Dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: teal
        accent: teal
        toggle:
          icon: material/toggle-switch
          name: Switch to light mode

nav:
    - Introduction: index.md
    - Virtual Environment: virtual_env.md
    - Code Standards: code-standards.md
    - GIT: git.md
    - DVC: dvc.md
    - Model Version Control: mlflow.md
    - Using GPU: gpu.md
    - Security: security.md
    - Optimization:
        - Model: opt-model.md
        - Data: opt-data.md
        - Concurrency & Parallelism: opt-para-concurr.md
        - Spark: opt-spark.md
    - Logging: logging.md
    - Deployment:
        - Flask: deploy-flask.md
        - FastAPI: deploy-fastapi.md
        - TF Serving: deploy-tf-serving.md
        - Serverless: deploy-serverless.md
        - Terraform: deploy-terraform.md
    - Docker: docker.md
    - Testing:
        - Overview & Pytest: testing-pytest.md
        - Schema Testing: testing-schema.md
        - ML Testing: testing-ml.md
        - API Testing: testing-api.md
        - Profiling: testing-profiling.md
    - CI/CD: cicd.md
    # - MLOps: mlops.md
    - Demo Site: demo.md
    # - Monitoring: monitoring.md

repo_name: mapattacker/ai-engineer
repo_url: https://github.com/mapattacker/ai-engineer

markdown_extensions:
    - admonition
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg